### ISSUE TITLE
DS1302 GPIOs

### ISSUE THREAD

**Issue by JieffeEl** [maarten-pennings/303WIFILC01#1]
For those interested in using the DS1302 RTC (e.g. use it to sync the time, only connecting to the Wifi to update it once or twice a day through NTP), the GPIOs are the following : 

```
DS1302 CLK	GPIO16
DS1302 CE	GPIO05	
DS1302 IO	GPIO14	
```

**Comment by maarten-pennings** [comment]
Thanks @[JieffeEl](https://github.com/JieffeEl), I have added it, see https://github.com/maarten-pennings/303WIFILC01/tree/main/1-pcbnets#gpio-nets-timekeeping
