### ISSUE TITLE
Web interface code?

### ISSUE THREAD

**Issue by ae-zero** [maarten-pennings/303WIFILC01#2]
Hello!

Just wanted to start by saying I love this project!  You totally saved this formerly useless clock that I bought!

I'm looking to make my own version to integrate with my homebrew home automation (specifically to display my pool temperature), but I noticed the configuration web interface code seems to be missing from the 5-clock directory.

Would it be possible to add the missing code?

Thanks!

ae-zero

**Comment by maarten-pennings** [comment]
Hi @ae-zero ,

Indeed it is not very well indicated. I guess you are referring to the Cfg library.
```
#include` <Cfg.h> // A library that lets a user configure an ESP8266 app (https://github.com/maarten-pennings/Cfg)
#include "led.h"
```

**Comment by maarten-pennings** [comment]
Added remark to readme

**Comment by ae-zero** [comment]
Awesome, thanks!
