### ISSUE TITLE
Not syncing with NTP server [solved]

### ISSUE THREAD

**Issue by devicemodder** [maarten-pennings/303WIFILC01#7]
Updated the firmware in my clock recently with this firmware. Code runs fine, and I connected it to my wifi, but it isn't pulling in time from the NTP servers. 

The display always shows ntp and doesn't do anything else.

**Comment by devicemodder** [comment]
nevermind, figured it out. arduino IDE used NONOS sdk version 2.2.1+ 100, thus not allowing the clock to connect to wifi for some odd reason

version 2.2.1 (Legacy) is needed if using a more modern router like the ones from asus. 

Might be good to add that to your readme, in case anyone has wifi issues.

**Comment by maarten-pennings** [comment]
Hi, this NonOS is completely new for me, so I'm not sure what to write. Do you have a suggestion for the readme?

Thinking asking these lines:

> If you have a newer router you need an older version of the ESP8266 board in Arduino (max ?.?.?). Newer board versions use NonOS version 2.2.1+ which does not support new routers, and is no longer maintained.
